---
logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  profiles:
    active: development
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always

server:
  address: 0.0.0.0
  port: 8080