spring:
  datasource:
    url: jdbc:postgresql://${HOST}:${DB_PORT}/${DATABASE}?password=${PASSWORD}&user=${USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

rsa:
  private-key: file:/etc/secrets/private.pem
  public-key: file:/etc/secrets/public.pem