spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}